/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfAccountResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfAccountResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfAccountResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountCreateDto"];
                    "text/json": components["schemas"]["AccountCreateDto"];
                    "application/*+json": components["schemas"]["AccountCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfAccountResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfAccountResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfAccountResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfAccountResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfAccountResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfAccountResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfAccountResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfAccountResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfAccountResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfTokenPairDto"];
                        "application/json": components["schemas"]["ApiResponseOfTokenPairDto"];
                        "text/json": components["schemas"]["ApiResponseOfTokenPairDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequestDto"];
                    "text/json": components["schemas"]["RefreshRequestDto"];
                    "application/*+json": components["schemas"]["RefreshRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfTokenPairDto"];
                        "application/json": components["schemas"]["ApiResponseOfTokenPairDto"];
                        "text/json": components["schemas"]["ApiResponseOfTokenPairDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequestDto"];
                    "text/json": components["schemas"]["ChangePasswordRequestDto"];
                    "application/*+json": components["schemas"]["ChangePasswordRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfBranchResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfBranchResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfBranchResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BranchCreateDto"];
                    "text/json": components["schemas"]["BranchCreateDto"];
                    "application/*+json": components["schemas"]["BranchCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfBranchResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfBranchResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfBranchResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfBranchResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfBranchResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfBranchResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfCompanyResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfCompanyResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfCompanyResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompanyCreateDto"];
                    "text/json": components["schemas"]["CompanyCreateDto"];
                    "application/*+json": components["schemas"]["CompanyCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCompanyResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfCompanyResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfCompanyResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCompanyResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfCompanyResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfCompanyResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfCurrencyResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfCurrencyResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfCurrencyResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CurrencyCreateDto"];
                    "text/json": components["schemas"]["CurrencyCreateDto"];
                    "application/*+json": components["schemas"]["CurrencyCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/currencies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/currencies/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfCurrencyResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fiscal-periods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fiscal-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FiscalPeriodCreateDto"];
                    "text/json": components["schemas"]["FiscalPeriodCreateDto"];
                    "application/*+json": components["schemas"]["FiscalPeriodCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fiscal-periods/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFiscalPeriodResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fiscal-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfFiscalYearResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfFiscalYearResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfFiscalYearResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FiscalYearCreateDto"];
                    "text/json": components["schemas"]["FiscalYearCreateDto"];
                    "application/*+json": components["schemas"]["FiscalYearCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fiscal-years/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fiscal-years/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFiscalYearResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fx-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfFxRateResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfFxRateResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfFxRateResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FxRateCreateDto"];
                    "text/json": components["schemas"]["FxRateCreateDto"];
                    "application/*+json": components["schemas"]["FxRateCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFxRateResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFxRateResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFxRateResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fx-rates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfFxRateResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfFxRateResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfFxRateResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    branchId?: string;
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfJournalEntryListItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfJournalEntryListItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfJournalEntryListItemDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostJournalEntryRequestDto"];
                    "text/json": components["schemas"]["PostJournalEntryRequestDto"];
                    "application/*+json": components["schemas"]["PostJournalEntryRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal-entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal-entries/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReverseJournalEntryRequestDto"];
                    "text/json": components["schemas"]["ReverseJournalEntryRequestDto"];
                    "application/*+json": components["schemas"]["ReverseJournalEntryRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfJournalEntryResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfstring"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfstring"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfstring"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    branchId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfObject"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenameRoleRequestDto"];
                    "text/json": components["schemas"]["RenameRoleRequestDto"];
                    "application/*+json": components["schemas"]["RenameRoleRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfRoleResponseDto"];
                        "application/json": components["schemas"]["ApiResponseOfRoleResponseDto"];
                        "text/json": components["schemas"]["ApiResponseOfRoleResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountCreateDto: {
            /** Format: uuid */
            companyId: string;
            code: string;
            name: string;
            accountType: components["schemas"]["AccountType"];
            normalBalance: components["schemas"]["NormalBalance"];
            isPostable?: boolean;
            /** Format: uuid */
            parentAccountId?: null | string;
            /** Format: uuid */
            currencyId?: null | string;
            systemAccountRole?: null | components["schemas"]["SystemAccountRole"];
        };
        AccountResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            code: string;
            name: string;
            accountType: components["schemas"]["AccountType"];
            normalBalance: components["schemas"]["NormalBalance"];
            isPostable: boolean;
            /** Format: uuid */
            parentAccountId?: null | string;
            /** Format: uuid */
            currencyId?: null | string;
            systemAccountRole?: null | components["schemas"]["SystemAccountRole"];
            isActive: boolean;
        };
        /** @enum {integer} */
        AccountType: 1 | 2 | 3 | 4 | 5;
        ApiResponseOfAccountResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["AccountResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfBranchResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["BranchResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfCompanyResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["CompanyResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfCurrencyResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["CurrencyResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfFiscalPeriodResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["FiscalPeriodResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfFiscalYearResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["FiscalYearResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfFxRateResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["FxRateResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfIReadOnlyListOfObject: {
            success?: boolean;
            message?: null | string;
            data?: null | unknown[];
            traceId?: null | string;
        };
        ApiResponseOfIReadOnlyListOfstring: {
            success?: boolean;
            message?: null | string;
            data?: null | string[];
            traceId?: null | string;
        };
        ApiResponseOfJournalEntryResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["JournalEntryResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfObject: {
            success?: boolean;
            message?: null | string;
            data?: unknown;
            traceId?: null | string;
        };
        ApiResponseOfPagedResponseOfAccountResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["PagedResponseOfAccountResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfPagedResponseOfBranchResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["PagedResponseOfBranchResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfPagedResponseOfCompanyResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["PagedResponseOfCompanyResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfPagedResponseOfCurrencyResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["PagedResponseOfCurrencyResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfPagedResponseOfFiscalYearResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["PagedResponseOfFiscalYearResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfPagedResponseOfFxRateResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["PagedResponseOfFxRateResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfPagedResponseOfJournalEntryListItemDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["PagedResponseOfJournalEntryListItemDto"];
            traceId?: null | string;
        };
        ApiResponseOfRoleResponseDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["RoleResponseDto"];
            traceId?: null | string;
        };
        ApiResponseOfTokenPairDto: {
            success?: boolean;
            message?: null | string;
            data?: null | components["schemas"]["TokenPairDto"];
            traceId?: null | string;
        };
        BranchCreateDto: {
            /** Format: uuid */
            companyId: string;
            code: string;
            name: string;
        };
        BranchResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            code: string;
            name: string;
            isActive: boolean;
        };
        ChangePasswordRequestDto: {
            currentPassword: string;
            newPassword: string;
        };
        CompanyCreateDto: {
            code: string;
            name: string;
            /** Format: uuid */
            baseCurrencyId: string;
        };
        CompanyResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** Format: uuid */
            baseCurrencyId: string;
            baseCurrencyCode: string;
            fxRoundingToleranceBase: string;
            isBaseCurrencyLocked: boolean;
            isActive: boolean;
        };
        CurrencyCreateDto: {
            code: string;
            name: string;
            symbol?: null | string;
            /** Format: uint8 */
            decimalPlaces?: number | string;
        };
        CurrencyResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            symbol?: null | string;
            /** Format: uint8 */
            decimalPlaces: number | string;
            isActive: boolean;
        };
        FiscalPeriodCreateDto: {
            /** Format: uuid */
            fiscalYearId: string;
            /** Format: uint8 */
            periodNumber?: number | string;
            periodType: components["schemas"]["FiscalPeriodType"];
            name: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
        };
        FiscalPeriodResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fiscalYearId: string;
            /** Format: uint8 */
            periodNumber: number | string;
            periodType: components["schemas"]["FiscalPeriodType"];
            name: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            isClosed: boolean;
        };
        /** @enum {integer} */
        FiscalPeriodType: 1 | 2;
        FiscalYearCreateDto: {
            /** Format: uuid */
            companyId: string;
            code: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
        };
        FiscalYearResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            code: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            isClosed: boolean;
        };
        FxRateCreateDto: {
            /** Format: uuid */
            fromCurrencyId: string;
            /** Format: uuid */
            toCurrencyId: string;
            rate: string;
            /** Format: date */
            rateDate: string;
            rateSource: components["schemas"]["FxRateSource"];
        };
        FxRateResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fromCurrencyId: string;
            fromCurrencyCode: string;
            /** Format: uuid */
            toCurrencyId: string;
            toCurrencyCode: string;
            rate: string;
            /** Format: date */
            rateDate: string;
            rateSource: components["schemas"]["FxRateSource"];
        };
        /** @enum {integer} */
        FxRateSource: 1 | 2 | 3;
        JournalEntryListItemDto: {
            /** Format: uuid */
            id: string;
            documentNumber: string;
            /** Format: uuid */
            branchId: string;
            /** Format: date */
            postingDate: string;
            /** Format: date */
            documentDate: string;
            sourceModule: components["schemas"]["JournalSourceModule"];
            /** Format: uuid */
            reversalOfJournalEntryId?: null | string;
            description?: null | string;
        };
        JournalEntryResponseDto: {
            /** Format: uuid */
            id: string;
            documentNumber: string;
            /** Format: uuid */
            transactionId: string;
            /** Format: uuid */
            branchId: string;
            /** Format: uuid */
            fiscalPeriodId: string;
            /** Format: date */
            postingDate: string;
            /** Format: date */
            documentDate: string;
            sourceModule: components["schemas"]["JournalSourceModule"];
            /** Format: uuid */
            reversalOfJournalEntryId?: null | string;
            description?: null | string;
            lines?: components["schemas"]["JournalLineResponseDto"][];
        };
        JournalLineCreateDto: {
            /** Format: uuid */
            accountId: string;
            description?: null | string;
            /** Format: uuid */
            currencyId: string;
            exchangeRate: string;
            /** Format: date */
            exchangeRateDate: string;
            debitFC?: string;
            creditFC?: string;
            debitBase?: string;
            creditBase?: string;
        };
        JournalLineResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: int16 */
            lineNumber: number | string;
            /** Format: uuid */
            accountId: string;
            accountCode: string;
            accountName: string;
            /** Format: uuid */
            currencyId: string;
            currencyCode: string;
            exchangeRate: string;
            /** Format: date */
            exchangeRateDate: string;
            debitFC: string;
            creditFC: string;
            debitBase: string;
            creditBase: string;
            description?: null | string;
        };
        /** @enum {integer} */
        JournalSourceModule: 1 | 2 | 3 | 4;
        LoginRequestDto: {
            userName: string;
            password: string;
            companyCode?: null | string;
        };
        /** @enum {integer} */
        NormalBalance: 0 | 1;
        PagedResponseOfAccountResponseDto: {
            data?: components["schemas"]["AccountResponseDto"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
        };
        PagedResponseOfBranchResponseDto: {
            data?: components["schemas"]["BranchResponseDto"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
        };
        PagedResponseOfCompanyResponseDto: {
            data?: components["schemas"]["CompanyResponseDto"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
        };
        PagedResponseOfCurrencyResponseDto: {
            data?: components["schemas"]["CurrencyResponseDto"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
        };
        PagedResponseOfFiscalYearResponseDto: {
            data?: components["schemas"]["FiscalYearResponseDto"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
        };
        PagedResponseOfFxRateResponseDto: {
            data?: components["schemas"]["FxRateResponseDto"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
        };
        PagedResponseOfJournalEntryListItemDto: {
            data?: components["schemas"]["JournalEntryListItemDto"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
        };
        PostJournalEntryRequestDto: {
            /** Format: uuid */
            branchId: string;
            /** Format: date */
            postingDate: string;
            /** Format: date */
            documentDate?: null | string;
            description?: null | string;
            sourceModule: components["schemas"]["JournalSourceModule"];
            lines: components["schemas"]["JournalLineCreateDto"][];
        };
        RefreshRequestDto: {
            refreshToken: string;
        };
        RenameRoleRequestDto: {
            name: string;
        };
        ReverseJournalEntryRequestDto: {
            /** Format: date */
            postingDate: string;
            /** Format: date */
            documentDate: string;
            description?: null | string;
        };
        RoleResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            isSystemRole: boolean;
            isActive: boolean;
        };
        /** @enum {integer} */
        SystemAccountRole: 1 | 2 | 3 | 4 | 5;
        TokenPairDto: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
