// <auto-generated />
using System;
using ErpApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpApi.Core.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AccountType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPostable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("NormalBalance")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("SystemAccountRole")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ParentAccountId")
                        .HasDatabaseName("IX_Account_ParentAccountId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CompanyId", "AccountType")
                        .HasDatabaseName("IX_Account_CompanyId_AccountType");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Account_CompanyId_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CompanyId", "SystemAccountRole")
                        .IsUnique()
                        .HasDatabaseName("UQ_Account_CompanyId_SystemRole")
                        .HasFilter("[SystemAccountRole] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasTrigger("TR_Account_ValidateConfiguration");

                            t.HasCheckConstraint("CK_Account_NormalBalance", "[NormalBalance] IN (0, 1)");

                            t.HasCheckConstraint("CK_Account_NormalBalanceMatchesType", "([AccountType] IN (1, 5) AND [NormalBalance] = 0) OR ([AccountType] IN (2, 3, 4) AND [NormalBalance] = 1)");

                            t.HasCheckConstraint("CK_Account_SystemRole", "[SystemAccountRole] IS NULL OR ([SystemAccountRole] >= 1 AND [SystemAccountRole] <= 5)");

                            t.HasCheckConstraint("CK_Account_SystemRolePostable", "[SystemAccountRole] IS NULL OR [IsPostable] = 1");

                            t.HasCheckConstraint("CK_Account_Type", "[AccountType] >= 1 AND [AccountType] <= 5");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogEntry_UserId_CreatedAt");

                    b.HasIndex("EntityName", "EntityKey", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogEntry_Entity_Key_CreatedAt");

                    b.ToTable("AuditLogEntries", null, t =>
                        {
                            t.HasTrigger("TR_AuditLogEntry_PreventModification");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Branch_CompanyId_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("ErpApi.Core.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FxRoundingToleranceBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasDefaultValue(1.0000m);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBaseCurrencyLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Company_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Companies", null, t =>
                        {
                            t.HasTrigger("TR_Company_ProtectBaseCurrencyLock");

                            t.HasCheckConstraint("CK_Company_FxRoundingTolerance", "[FxRoundingToleranceBase] >= 0 AND [FxRoundingToleranceBase] <= 1");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Currency_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Currencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currency_DecimalPlaces", "[DecimalPlaces] >= 0 AND [DecimalPlaces] <= 4");
                        });
                });

            modelBuilder.Entity("ErpApi.Core.Models.FiscalPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("PeriodNumber")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PeriodType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("FiscalYearId", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_FiscalPeriod_FiscalYearId_PeriodNumber");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_FiscalPeriod_StartDate_EndDate");

                    b.ToTable("FiscalPeriods", null, t =>
                        {
                            t.HasTrigger("TR_FiscalPeriod_PreventOverlap");

                            t.HasTrigger("TR_FiscalPeriod_WithinYearRange");

                            t.HasCheckConstraint("CK_FiscalPeriod_DateOrder", "[EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_FiscalPeriod_Number", "[PeriodNumber] >= 1 AND [PeriodNumber] <= 14");

                            t.HasCheckConstraint("CK_FiscalPeriod_Type", "[PeriodType] IN (1, 2)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.FiscalYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_FiscalYear_CompanyId_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("FiscalYears", null, t =>
                        {
                            t.HasTrigger("TR_FiscalYear_PreventCloseWithOpenPeriods");

                            t.HasTrigger("TR_FiscalYear_PreventOverlap");

                            t.HasCheckConstraint("CK_FiscalYear_DateOrder", "[EndDate] > [StartDate]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<byte>("RateSource")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ToCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ToCurrencyId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("FromCurrencyId", "ToCurrencyId", "RateDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_FxRate_From_To_Date");

                    b.HasIndex("FromCurrencyId", "ToCurrencyId", "RateDate", "RateSource")
                        .IsUnique()
                        .HasDatabaseName("UQ_FxRate_From_To_Date_Source")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("FxRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_FxRate_DifferentCurrencies", "[FromCurrencyId] <> [ToCurrencyId]");

                            t.HasCheckConstraint("CK_FxRate_RatePositive", "[Rate] > 0");

                            t.HasCheckConstraint("CK_FxRate_RateSource", "[RateSource] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ErpApi.Core.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("FiscalPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ReversalOfJournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SourceModule")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FiscalPeriodId")
                        .HasDatabaseName("IX_JournalEntry_FiscalPeriodId");

                    b.HasIndex("PostingDate")
                        .HasDatabaseName("IX_JournalEntry_PostingDate");

                    b.HasIndex("ReversalOfJournalEntryId")
                        .IsUnique()
                        .HasDatabaseName("UQ_JournalEntry_ReversalOf")
                        .HasFilter("[ReversalOfJournalEntryId] IS NOT NULL");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_JournalEntry_TransactionId");

                    b.HasIndex("BranchId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_JournalEntry_BranchId_DocumentNumber");

                    b.ToTable("JournalEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_JournalEntry_DocumentDateNotAfterPostingDate", "[DocumentDate] <= [PostingDate]");

                            t.HasCheckConstraint("CK_JournalEntry_NotSelfReversal", "[ReversalOfJournalEntryId] IS NULL OR [ReversalOfJournalEntryId] <> [Id]");

                            t.HasCheckConstraint("CK_JournalEntry_SourceModule", "[SourceModule] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("ErpApi.Core.Models.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("CreditBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("CreditFC")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DebitBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("DebitFC")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<DateOnly>("ExchangeRateDate")
                        .HasColumnType("date");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_JournalLine_AccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("JournalEntryId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_JournalLine_JournalEntryId_LineNumber");

                    b.ToTable("JournalLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_JournalLine_BaseEqualsConverted", "ABS([DebitBase] - ROUND([DebitFC] * [ExchangeRate], 4)) <= 0.0001 AND ABS([CreditBase] - ROUND([CreditFC] * [ExchangeRate], 4)) <= 0.0001");

                            t.HasCheckConstraint("CK_JournalLine_DebitXorCredit", "([DebitFC] > 0 AND [CreditFC] = 0 AND [DebitBase] > 0 AND [CreditBase] = 0) OR ([CreditFC] > 0 AND [DebitFC] = 0 AND [CreditBase] > 0 AND [DebitBase] = 0)");

                            t.HasCheckConstraint("CK_JournalLine_ExchangeRatePositive", "[ExchangeRate] > 0");
                        });
                });

            modelBuilder.Entity("ErpApi.Core.Models.NumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<byte>("DocumentType")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("FiscalYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PaddingLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)6);

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CompanyId", "BranchId", "DocumentType", "FiscalYearId")
                        .IsUnique()
                        .HasDatabaseName("UQ_NumberSequence_Scope");

                    b.ToTable("NumberSequences", null, t =>
                        {
                            t.HasTrigger("TR_NumberSequence_PreventDelete");

                            t.HasCheckConstraint("CK_NumberSequence_CurrentValue", "[CurrentValue] >= 0");

                            t.HasCheckConstraint("CK_NumberSequence_JournalScope", "[DocumentType] <> 1 OR [BranchId] IS NOT NULL");

                            t.HasCheckConstraint("CK_NumberSequence_Padding", "[PaddingLength] >= 1 AND [PaddingLength] <= 18");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshToken_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshToken_UserId");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshToken_ExpiresAfterCreation", "[ExpiresAt] > [CreatedAt]");
                        });
                });

            modelBuilder.Entity("ErpApi.Core.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Role_CompanyId_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ErpApi.Core.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ErpApi.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_CompanyId_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("CompanyId", "UserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_CompanyId_UserName")
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_SystemUserHasNoCompany", "([Id] = '00000000-0000-0000-0000-000000000001' AND [CompanyId] IS NULL) OR ([Id] <> '00000000-0000-0000-0000-000000000001' AND [CompanyId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ErpApi.Core.Models.UserBranch", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "BranchId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("UserBranches", null, t =>
                        {
                            t.HasTrigger("TR_UserBranch_ValidateCompanyBoundary");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", null, t =>
                        {
                            t.HasTrigger("TR_UserRole_ValidateCompanyBoundary");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ErpApi.Core.Models.Account", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ErpApi.Core.Models.Account", "ParentAccount")
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Currency");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("ErpApi.Core.Models.AuditLogEntry", b =>
                {
                    b.HasOne("ErpApi.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpApi.Core.Models.Branch", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErpApi.Core.Models.Company", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BaseCurrency");
                });

            modelBuilder.Entity("ErpApi.Core.Models.Currency", b =>
                {
                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ErpApi.Core.Models.FiscalPeriod", b =>
                {
                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("ErpApi.Core.Models.FiscalYear", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErpApi.Core.Models.FxRate", b =>
                {
                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.Currency", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.Currency", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("ErpApi.Core.Models.JournalEntry", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.FiscalPeriod", "FiscalPeriod")
                        .WithMany()
                        .HasForeignKey("FiscalPeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.JournalEntry", "ReversalOfJournalEntry")
                        .WithMany()
                        .HasForeignKey("ReversalOfJournalEntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");

                    b.Navigation("FiscalPeriod");

                    b.Navigation("ReversalOfJournalEntry");
                });

            modelBuilder.Entity("ErpApi.Core.Models.JournalLine", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Currency");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("ErpApi.Core.Models.NumberSequence", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ErpApi.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("ErpApi.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("ErpApi.Core.Models.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ErpApi.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpApi.Core.Models.Role", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErpApi.Core.Models.RolePermission", b =>
                {
                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ErpApi.Core.Models.User", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErpApi.Core.Models.UserBranch", b =>
                {
                    b.HasOne("ErpApi.Core.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpApi.Core.Models.UserRole", b =>
                {
                    b.HasOne("ErpApi.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ErpApi.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpApi.Core.Models.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
